create table if not exists public.analysis_usage (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.accounts(id) on delete cascade,
  model text not null,
  input_tokens bigint not null default 0 check (input_tokens >= 0),
  answer_tokens bigint not null default 0 check (answer_tokens >= 0),
  thinking_tokens bigint not null default 0 check (thinking_tokens >= 0),
  output_tokens bigint not null default 0 check (output_tokens >= 0),
  total_tokens bigint not null default 0 check (total_tokens >= 0),
  estimated_cost_usd numeric(18,10) not null default 0 check (estimated_cost_usd >= 0),
  created_at timestamptz not null default now()
);

create index if not exists analysis_usage_account_id_idx on public.analysis_usage(account_id);
create index if not exists analysis_usage_created_at_idx on public.analysis_usage(created_at desc);

alter table public.analysis_usage enable row level security;
revoke all on public.analysis_usage from anon, authenticated;

notify pgrst, 'reload schema';
